In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
pd.__version__

'0.23.4'

## Exercise 1

In [25]:
medals_raw = pd.read_csv('D:\medals.csv')
#imported the csv file

In [31]:
medals_raw.groupby(["Medal"]).agg({"Athlete":"nunique"})
#grouped the medals per category

        Athlete
Medal
Bronze    10008
Gold       8844
Silver     9713

In [30]:
athlete_with_medals = medals_raw[medals_raw["Sport"] == "Athletics"].groupby(["Athlete"]).agg({"Gold":"sum", "Silver":"sum", "Bronze":"sum", "Event":"nunique"})
athlete_with_medals

athlete_with_gold = athlete_with_medals[athlete_with_medals["Gold"] != 0]
top_five_athlete_with_gold = athlete_with_gold.loc[:, ["Gold"]].sort_values(by="Gold", ascending=False).head(5)
top_five_athlete_with_gold

#created 'top_five_athlete_with_gold' dataframe with top 5 athletes

               Gold
Athlete
Carl Lewis       29
Usain Bolt        9
Paavo Nurmi       9
Allyson Felix     6
Ville Ritola      5

## Exercise 2

In [32]:
athlete_with_medals = medals_raw[medals_raw["Medal"]=="Gold"].groupby(["Athlete"]).agg({"Gold":"sum", "Event":"nunique"})
athlete_with_medals
top_five_gold_events = athlete_with_medals.loc[:, ["Event", "Gold"]].sort_values(by=["Event", "Gold"], ascending=False).head()
top_five_gold_events

# top five athletes who won gold medals in the largest number of different athletic events

                Event  Gold
Athlete
Michael Phelps     13    23
Mark Spitz          7     9
Paavo Nurmi         6     9
Usain Bolt          6     9
Boris Shakhlin      6     7

### Exercise 3

 ### Structure of the algorithm

#### ** Alocate an unique ID for each event of the games in corresponding year
#### ** Create dataframes for each athlete to be eliminated  
#### ** Find in 'events_id' dataframe the matching IDs of the athletes events to be eliminated and use Loop to make the changes: 
- for each id where 'first_athlet.id' OR 'third_athlet.id' = events_id.id check 
if Medal is Silver 
then update Medal = Gold and Gold = 1 and Silver = 0 
if Medal is Bronze 
then update Medal = Silver and Silver = 1 and Bronze = 0
- delete rows with conditions: event_id[(event_id.Athlete == 'Michael Phelps') & (event_id.Medal == "Gold")]

#### ** Export the dataset 
#### ** Top 5 gold medals

In [26]:
events_id = medals_raw.assign(id=(medals_raw['Games'] + '_' + medals_raw['Event']).astype('category').cat.codes)
events_id

#grouped the events by an unique ID

,Games,Year,Sport,Discipline,Athlete,Team,Gender,Event,Medal,Gold,Silver,Bronze,id
0,Athens (1896),1896,Aquatics,Swimming,alfred hajos,HUN,Men,100m freestyle men,Gold,1,0,0,257
1,Athens (1896),1896,Aquatics,Swimming,Otto Herschmann,AUT,Men,100m freestyle men,Silver,0,1,0,257
2,Athens (1896),1896,Aquatics,Swimming,dimitrios drivas,GRE,Men,100m freestyle for sailors men,Bronze,0,0,1,256
3,Athens (1896),1896,Aquatics,Swimming,Ioannis Malokinis,GRE,Men,100m freestyle for sailors men,Gold,1,0,0,256
4,Athens (1896),1896,Aquatics,Swimming,spiridon chasapis,GRE,Men,100m freestyle for sailors men,Silver,0,1,0,256
5,Athens (1896),1896,Aquatics,Swimming,Efstathios Chorophas,GRE,Men,1200m freestyle men,Bronze,0,0,1,262
6,Athens (1896),1896,Aquatics,Swimming,alfred hajos,HUN,Men,1200m freestyle men,Gold,1,0,0,262
7,Athens (1896),1896,Aquatics,Swimming,joannis andreou,GRE,Men,1200m freestyle men,Silver,0,1,0,262
8,Athens (1896),1896,Aquatics,Swimming,Efstathios Chorophas,GRE,Men,400m freestyle men,Bronze,0,0,1,267
9,Athens (1896),1896,Aquatics,Swimming,paul neumann,AUT,Men,400m freestyle men,Gold,1,0,0,267
10,Athens (1896),1896,Aquatics,Swimming,Antonios Pepanos,GRE,Men,400m freestyle men,Silver,0,1,0,267
11,Athens (1896),1896,Athletics,Athletics,Francis Lane,USA,Men,100m men,Bronze,0,0,1,258
12,Athens (1896),1896,Athletics,Athletics,Alajos Szokolyi,HUN,Men,100m men,Bronze,0,0,1,258
13,Athens (1896),1896,Athletics,Athletics,Thomas Burke,USA,Men,100m men,Gold,1,0,0,258
14,Athens (1896),1896,Athletics,Athletics,Fritz Hofmann,GER,Men,100m men,Silver,0,1,0,258
15,Athens (1896),1896,Athletics,Athletics,Thomas Curtis,USA,Men,110m hurdles men,Gold,1,0,0,260
16,Athens (1896),1896,Athletics,Athletics,Grantley Goulding,GBR,Men,110m hurdles men,Silver,0,1,0,260
17,Athens (1896),1896,Athletics,Athletics,Albin Lermusiaux,FRA,Men,1500m men,Bronze,0,0,1,263
18,Athens (1896),1896,Athletics,Athletics,Edwin Flack,AUS,Men,1500m men,Gold,1,0,0,263
19,Athens (1896),1896,Athletics,Athletics,Arthur Blake,USA,Men,1500m men,Silver,0,1,0,263
20,Athens (1896),1896,Athletics,Athletics,Charles Gmelin,GBR,Men,400m men,Bronze,0,0,1,268
21,Athens (1896),1896,Athletics,Athletics,Thomas Burke,USA,Men,400m men,Gold,1,0,0,268
22,Athens (1896),1896,Athletics,Athletics,Herbert Jamison,USA,Men,400m men,Silver,0,1,0,268
23,Athens (1896),1896,Athletics,Athletics,Dimitrios Golemis,GRE,Men,800m men,Bronze,0,0,1,270
24,Athens (1896),1896,Athletics,Athletics,Edwin Flack,AUS,Men,800m men,Gold,1,0,0,270
25,Athens (1896),1896,Athletics,Athletics,Nandor Dani,HUN,Men,800m men,Silver,0,1,0,270
26,Athens (1896),1896,Athletics,Athletics,Sotirios Versis,GRE,Men,discus throw men,Bronze,0,0,1,274
27,Athens (1896),1896,Athletics,Athletics,Robert Garrett,USA,Men,discus throw men,Gold,1,0,0,274
28,Athens (1896),1896,Athletics,Athletics,Panagiotis Paraskevopoulos,GRE,Men,discus throw men,Silver,0,1,0,274
29,Athens (1896),1896,Athletics,Athletics,Ellery Clark,USA,Men,high jump men,Gold,1,0,0,280
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33231,Rio (2016),2016,Hockey,Hockey,Christopher Wesley,GER,Unknown,hockey,Bronze,0,0,1,3605
33232,Rio (2016),2016,Handball,Handball,Fabian Wiede,GER,Unknown,handball,Bronze,0,0,1,3602
33233,Rio (2016),2016,Handball,Handball,Patrick Wiencek,GER,Unknown,handball,Bronze,0,0,1,3602
33234,Rio (2016),2016,Rowing,Rowing,Peter Wiersum,NED,Unknown,eight with coxswain (8+),Bronze,0,0,1,3594
33235,Rio (2016),2016,Rowing,Rowing,Tone Wieten,NED,Unknown,eight with coxswain (8+),Bronze,0,0,1,3594
33236,Rio (2016),2016,Football,Football,Rhian Wilkinson,CAN,Unknown,football,Bronze,0,0,1,3598
33237,Rio (2016),2016,Athletics,Athletics,Bianca Williams,GBR,Unknown,4x100m relay,Bronze,0,0,1,3523
33238,Rio (2016),2016,Rugby,Rugby,Charity Williams,CAN,Unknown,rugby,Bronze,0,0,1,3625
33239,Rio (2016),2016,Aquatics,Swimming,Michelle Williams,CAN,Unknown,4x100m freestyle relay,Bronze,0,0,1,3521
33240,Rio (2016),2016,Athletics,Athletics,Nicholas Willis,NZL,Unknown,1500m,Bronze,0,0,1,3497
33241,Rio (2016),2016,Gymnastics,Artistic Gymnastics,Nile Wilson,GBR,Unknown,horizontal bar,Bronze,0,0,1,3606
33242,Rio (2016),2016,Handball,Handball,Andreas Wolff,GER,Unknown,handball,Bronze,0,0,1,3602
33243,Rio (2016),2016,Taekwondo,Taekwondo,Panipak Wongpattanakit,THA,Unknown,- 49 kg,Bronze,0,0,1,3477
33244,Rio (2016),2016,Archery,Archery,Taylor Worth,AUS,Unknown,team round 60y,Bronze,0,0,1,3635
33245,Rio (2016),2016,Fencing,Fencing,Dagmara Wozniak,USA,Unknown,sabre team,Bronze,0,0,1,3627
33246,Rio (2016),2016,Judo,Judo,Kanae Yamabe,JPN,Unknown,+ 78kg (heavyweight),Bronze,0,0,1,3470
33247,Rio (2016),2016,Wrestling,Wrestling Freestyle,Elitsa Atanasova Yankova,BUL,Unknown,- 48kg (light-flyweight),Bronze,0,0,1,3476
33248,Rio (2016),2016,Shooting,Shooting,Siling Yi,CHN,Unknown,10m air rifle (40 shots),Bronze,0,0,1,3493
33249,Rio (2016),2016,Weightlifting,Weightlifting,Jin Hee Yoon,KOR,Unknown,53kg,Bronze,0,0,1,3536
33250,Rio (2016),2016,Aquatics,Swimming,Kurumi Yoshida,JPN,Unknown,100m freestyle,Bronze,0,0,1,3490
33251,Rio (2016),2016,Gymnastics,Artistic Gymnastics,Hao You,CHN,Unknown,"team, horizontal bar",Bronze,0,0,1,3636
33252,Rio (2016),2016,Judo,Judo,Song Yu,CHN,Unknown,+ 78kg (heavyweight),Bronze,0,0,1,3470
33253,Rio (2016),2016,Football,Football,Shelina Zadorsky,CAN,Unknown,football,Bronze,0,0,1,3598
33254,Rio (2016),2016,Fencing,Fencing,Mariel Zagunis,USA,Unknown,sabre team,Bronze,0,0,1,3627
33255,Rio (2016),2016,Weightlifting,Weightlifting,Alexandr Zaichikov,KAZ,Unknown,+ 105kg,Bronze,0,0,1,3467
33256,Rio (2016),2016,Sailing,Sailing,Thomas Zajac,AUT,Unknown,0.5-1t,Bronze,0,0,1,3483
33257,Rio (2016),2016,Gymnastics,Artistic Gymnastics,Chenglong Zhang,CHN,Unknown,"team, horizontal bar",Bronze,0,0,1,3636
33258,Rio (2016),2016,Wrestling,Wrestling Freestyle,Fengliu Zhang,CHN,Unknown,67.5 - 75kg (middleweight),Bronze,0,0,1,3552
33259,Rio (2016),2016,Badminton,Badminton,Yunlei Zhao,CHN,Unknown,doubles,Bronze,0,0,1,3593
33260,Rio (2016),2016,Hockey,Hockey,Martin Zwicker,GER,Unknown,hockey,Bronze,0,0,1,3605

### Dataset with the first Athlet Gold winning Games - Michael Phelps

In [27]:
First_athlet = event_id[(event_id.Athlete == 'Michael Phelps') & (event_id.Medal == "Gold")]
First_athlet

,Games,Year,Sport,Discipline,Athlete,Team,Gender,Event,Medal,Gold,Silver,Bronze,id
25236,Athens (2004),2004,Aquatics,Swimming,Michael Phelps,USA,Men,100m butterfly men,Gold,1,0,0,318
25264,Athens (2004),2004,Aquatics,Swimming,Michael Phelps,USA,Men,200m butterfly men,Gold,1,0,0,342
25276,Athens (2004),2004,Aquatics,Swimming,Michael Phelps,USA,Men,200m individual medley men,Gold,1,0,0,346
25288,Athens (2004),2004,Aquatics,Swimming,Michael Phelps,USA,Men,400m individual medley men,Gold,1,0,0,361
25336,Athens (2004),2004,Aquatics,Swimming,Michael Phelps,USA,Men,4x100m medley relay men,Gold,1,0,0,376
25372,Athens (2004),2004,Aquatics,Swimming,Michael Phelps,USA,Men,4x200m freestyle relay men,Gold,1,0,0,380
27235,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,100m butterfly men,Gold,1,0,0,1079
27263,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,200m butterfly men,Gold,1,0,0,1101
27269,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,200m freestyle men,Gold,1,0,0,1103
27275,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,200m individual medley men,Gold,1,0,0,1105
27287,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,400m individual medley men,Gold,1,0,0,1121
27302,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,4x100m freestyle relay men,Gold,1,0,0,1134
27338,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,4x100m medley relay men,Gold,1,0,0,1136
27377,Beijing (2008),2008,Aquatics,Swimming,Michael Phelps,USA,Men,4x200m freestyle relay men,Gold,1,0,0,1140
29227,London (2012),2012,Aquatics,Swimming,Michael Phelps,USA,Men,100m butterfly men,Gold,1,0,0,1855
29229,London (2012),2012,Aquatics,Swimming,Michael Phelps,USA,Men,200m individual medley men,Gold,1,0,0,1886
29231,London (2012),2012,Aquatics,Swimming,Michael Phelps,USA,Men,4x200m freestyle relay men,Gold,1,0,0,1919
29232,London (2012),2012,Aquatics,Swimming,Michael Phelps,USA,Men,4x100m medley relay men,Gold,1,0,0,1915
31180,Rio (2016),2016,Aquatics,Swimming,Michael Phelps,USA,Unknown,4x100m medley relay,Gold,1,0,0,3522
31181,Rio (2016),2016,Aquatics,Swimming,Michael Phelps,USA,Unknown,200m individual medley,Gold,1,0,0,3505
31182,Rio (2016),2016,Aquatics,Swimming,Michael Phelps,USA,Unknown,4x200m freestyle relay,Gold,1,0,0,3524
31183,Rio (2016),2016,Aquatics,Swimming,Michael Phelps,USA,Unknown,200m butterfly,Gold,1,0,0,3503
31184,Rio (2016),2016,Aquatics,Swimming,Michael Phelps,USA,Unknown,4x100m freestyle relay,Gold,1,0,0,3521

In [ ]:
### Dataset with the third Athlet Gold winning games - Paavo Nurmi

In [13]:
Third_athlet = event_id[(event_id.Athlete == 'Paavo Nurmi') & (event_id.Medal == "Gold")]
Third_athlet

,Games,Year,Sport,Discipline,Athlete,Team,Gender,Event,Medal,Gold,Silver,Bronze,id
2990,Antwerp (1920),1920,Athletics,Athletics,Paavo Nurmi,FIN,Men,10000m men,Gold,1,0,0,112
3062,Antwerp (1920),1920,Athletics,Athletics,Paavo Nurmi,FIN,Men,cross country individual men,Gold,1,0,0,193
3069,Antwerp (1920),1920,Athletics,Athletics,Paavo Nurmi,FIN,Men,cross country team men,Gold,1,0,0,194
4242,Paris (1924),1924,Athletics,Athletics,Paavo Nurmi,FIN,Men,1500m men,Gold,1,0,0,3366
4258,Paris (1924),1924,Athletics,Athletics,Paavo Nurmi,FIN,Men,3000m team men,Gold,1,0,0,3373
4298,Paris (1924),1924,Athletics,Athletics,Paavo Nurmi,FIN,Men,5000m men,Gold,1,0,0,3386
4304,Paris (1924),1924,Athletics,Athletics,Paavo Nurmi,FIN,Men,cross country individual men,Gold,1,0,0,3416
4314,Paris (1924),1924,Athletics,Athletics,Paavo Nurmi,FIN,Men,cross country team men,Gold,1,0,0,3417
5092,Amsterdam (1928),1928,Athletics,Athletics,Paavo Nurmi,FIN,Men,10000m men,Gold,1,0,0,8